# Generated by Django 3.1.8 on 2021-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
